version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Building website..."
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 sync . s3://my-project-bucket-10015 --delete
