version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - rm -rf node_modules package-lock.json  
      - npm install
      - chmod -R +x node_modules/.bin  

  build:
    commands:
      - npm run build
